import { defaultCustom, templates, normalizeCustom, parseObject, readPath, renderCustom } from './interface-config.js';

export function initSettings({ request, saved: onSaved }) {
  const $ = id => document.getElementById(id);
  let saved = { baseUrl: '', hasApiKey: false, provider: 'openai' }, currentProvider = 'openai';
  const drafts = {};
  const fields = { method: 'requestMethod', encoding: 'requestEncoding', body: 'requestBody', headers: 'requestHeaders', imageEncoding: 'imageEncoding', maxImages: 'maxImages', maxImageMB: 'maxImageMB', sizeSeparator: 'sizeSeparator', resultType: 'resultType', imagePath: 'imagePath', errorPath: 'errorPath' };
  localStorage.removeItem('studio-api-settings');
  const status = (text, kind = '') => { $('status').textContent = text; $('status').className = `status ${kind}`; };
  function hint() { $('apiKey').placeholder = saved.hasApiKey && currentProvider === saved.provider && $('baseUrl').value.trim().replace(/\/+$/, '') === saved.baseUrl ? '•••••••• 已保存，留空保留；输入以替换' : '填写 API Key'; }
  function customInput() { return Object.fromEntries(Object.entries(fields).map(([key, id]) => [key, ['maxImages', 'maxImageMB'].includes(key) ? Number($(id).value) : $(id).value])); }
  function inputs() { return { provider: currentProvider, name: $('serviceName').value.trim(), baseUrl: $('baseUrl').value.trim(), apiKey: $('apiKey').value.trim(), model: $('model').value.trim(), ...(currentProvider === 'custom' ? { custom: customInput() } : {}) }; }
  function setCustom(value) { for (const [key, id] of Object.entries(fields)) $(id).value = (value || defaultCustom)[key] ?? defaultCustom[key]; updateEncoding(); }
  function updateEncoding() {
    const multi = $('requestEncoding').value === 'multipart'; $('requestBodyLabel').textContent = multi ? '表单字段模板（JSON 编辑）' : '请求体模板'; $('bodyHelp').textContent = multi ? '每个键对应一个表单字段；{{images}} 展开为同名文件字段。' : '变量在发送时替换；图片数组保留数组类型。无参考图时省略图片字段。'; $('imageEncoding').disabled = multi; $('imageEncodingHelp').textContent = multi ? '直接上传原图文件，字段名由模板定义，例如 image[]。' : '图片来自本轮引用，顺序保持一致。'; document.querySelector('[data-insert-variable="content"]').disabled = multi;
  }
  function updateProvider() { const custom = currentProvider === 'custom', dashscope = currentProvider === 'dashscope'; $('customSettings').hidden = !custom; $('serviceNameField').hidden = !custom; $('baseUrlLabel').textContent = custom || dashscope ? '请求地址（完整 URL）' : 'API Base URL'; $('baseUrlHelp').textContent = custom || dashscope ? '填写完整生成地址，不会自动追加路径。密钥请放在 API Key 中，不放入 URL。' : '填写基础地址，接口路径由所选服务自动处理。'; $('baseUrl').placeholder = dashscope ? 'https://你的业务空间.cn-beijing.maas.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation' : custom ? 'https://api.example.com/v1/images/generations' : 'https://api.example.com/v1'; $('providerHint').textContent = dashscope ? 'DashScope 原生协议：最多 3 张参考图，每张不超过 10 MB；地址、Key 与模型必须属于同一地域和业务空间。' : custom ? '使用同步返回图片的接口，按服务文档填写配置。' : '支持标准图片生成和多图编辑接口。'; $('testConnection').textContent = custom || dashscope ? '检查配置' : '测试连接'; $('testHelp').textContent = custom ? '检查配置不联网、不生成图片。真实出图请保存后在创作页测试。' : dashscope ? '原生接口没有通用模型列表检查；此处只检查配置，真实出图请保存后在创作页测试。' : '测试连接只读取模型列表，不生成图片；无模型列表时可手填模型并保存。'; hint(); }
  function busy(value) { $('settings').setAttribute('aria-busy', value); for (const node of $('settings').querySelectorAll('button,input,textarea,select')) node.disabled = value; if (!value) updateEncoding(); }
  function selectTab(name, focus = false) { for (const key of ['request', 'response', 'check']) { $(key + 'Panel').hidden = key !== name; $(key + 'Tab').setAttribute('aria-selected', key === name); $(key + 'Tab').tabIndex = key === name ? 0 : -1; } if (name === 'check') preview(); if (focus) $(name + 'Tab').focus(); }
  ['request', 'response', 'check'].forEach((name, index) => { $(name + 'Tab').onclick = () => selectTab(name); $(name + 'Tab').onkeydown = event => { const target = event.key === 'ArrowRight' ? (index + 1) % 3 : event.key === 'ArrowLeft' ? (index + 2) % 3 : event.key === 'Home' ? 0 : event.key === 'End' ? 2 : null; if (target !== null) { event.preventDefault(); selectTab(['request', 'response', 'check'][target], true); } }; });
  function validate() { const value = inputs(); let url; try { url = new URL(value.baseUrl); } catch { throw new Error('请填写有效的 API 地址。'); } if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password || url.search || url.hash) throw new Error('API 地址不能包含账号、查询参数或锚点。'); if (!value.model) throw new Error('请填写图片模型名称。'); if (currentProvider === 'custom') value.custom = normalizeCustom(value.custom); return value; }
  function preview() { try { const config = normalizeCustom(customInput()); const images = ['data:image/png;base64,〈模特图〉', 'data:image/png;base64,〈服装图〉']; const rendered = renderCustom(config, { model: $('model').value || '〈模型名称〉', prompt: '让图片 1 中的模特穿上图片 2 中的服装。', images: config.imageEncoding === 'base64' ? ['〈模特图 Base64〉', '〈服装图 Base64〉'] : images, size: '1152x1536', apiKey: '••••••••' }); let text = config.method + ' ' + $('baseUrl').value + '\n\n' + JSON.stringify(rendered.headers, null, 2) + '\n\n' + (config.encoding === 'multipart' ? '表单字段（图片数组展开为文件）：\n' : 'JSON：\n') + JSON.stringify(rendered.fields, null, 2); if ($('apiKey').value) text = text.split($('apiKey').value).join('••••••••'); $('requestPreview').textContent = text; validate(); $('checkStatus').textContent = '配置格式检查通过。未联网，尚未验证出图。'; $('checkStatus').className = 'status success'; } catch (error) { $('requestPreview').textContent = '填写有效配置后显示请求预览。'; $('checkStatus').textContent = error.message; $('checkStatus').className = 'status error'; } }
  $('checkAgain').onclick = preview;
  $('tryExtract').onclick = () => { try { const config = normalizeCustom(customInput()); const result = readPath(parseObject($('responseSample').value, '返回示例'), config.imagePath); if (typeof result !== 'string' || !result) throw new Error('未找到图片字段，请检查示例和路径。'); if (config.resultType === 'url' && !/^https?:\/\//.test(result)) throw new Error('已找到字段，但它不是 HTTP 图片 URL。'); $('extractStatus').textContent = '已读取：' + result.slice(0, 500); $('extractStatus').className = 'status success'; } catch (error) { $('extractStatus').textContent = error.message; $('extractStatus').className = 'status error'; } };
  $('provider').onchange = () => { drafts[currentProvider] = { ...inputs(), apiKey: '' }; currentProvider = $('provider').value; const value = drafts[currentProvider] || { baseUrl: '', model: currentProvider === 'dashscope' ? 'qwen-image-3.0-pro' : '', name: '' }; $('baseUrl').value = value.baseUrl; $('model').value = value.model; $('serviceName').value = value.name || ''; $('apiKey').value = ''; $('models').replaceChildren(); if (currentProvider === 'custom') setCustom(value.custom); updateProvider(); status(''); };
  $('baseUrl').oninput = hint; $('requestEncoding').onchange = updateEncoding;
  document.querySelectorAll('[data-insert-variable]').forEach(button => button.onclick = () => { const editor = $('requestBody'); editor.setRangeText('{{' + button.dataset.insertVariable + '}}', editor.selectionStart, editor.selectionEnd, 'end'); editor.focus(); });
  $('interfaceTemplate').onchange = () => { const key = $('interfaceTemplate').value; if (!key) return; setCustom({ ...defaultCustom, ...templates[key] }); if (key === 'dashscope') $('model').value = 'qwen-image-3.0-pro'; $('responseSample').value = JSON.stringify(key === 'dashscope' ? { output: { choices: [{ message: { content: [{ image: 'https://example.com/generated-image.png' }] } }] } } : key === 'multipart' ? { data: [{ b64_json: '〈图片 Base64〉' }] } : { data: [{ url: 'https://example.com/generated-image.png' }] }, null, 2); $('interfaceTemplate').value = ''; $('extractStatus').textContent = ''; status('已载入模板，地址与密钥保持不变。'); };
  $('testConnection').onclick = async () => { let input; try { input = validate(); } catch (error) { return status(error.message, 'error'); } if (currentProvider === 'custom') selectTab('check'); busy(true); status(currentProvider === 'custom' || currentProvider === 'dashscope' ? '正在检查配置格式…' : '正在读取模型列表…'); try { const result = await request('/api/settings/test', input); $('models').replaceChildren(); if (!result.ok) return status(result.message, 'error'); for (const model of result.models || []) { const option = document.createElement('option'); option.value = model; $('models').append(option); } status(result.localOnly ? result.message : `连接成功，读取到 ${result.models.length} 个模型。图片编辑能力仍需实际出图验证。`, 'success'); } catch (error) { status(error.message, 'error'); } finally { busy(false); } };
  $('saveSettings').onclick = async () => { let input; try { input = validate(); } catch (error) { return status(error.message, 'error'); } busy(true); try { saved = await request('/api/settings', input); $('baseUrl').value = saved.baseUrl; $('apiKey').value = ''; hint(); status('设置已保存。返回创作即可生成图片。', 'success'); onSaved(); } catch (error) { status(error.message, 'error'); } finally { busy(false); } };
  setCustom(defaultCustom); $('responseSample').value = JSON.stringify({ output: { choices: [{ message: { content: [{ image: 'https://example.com/generated-image.png' }] } }] } }, null, 2); busy(true);
  request('/api/settings').then(result => { saved = { ...result, provider: result.provider || 'openai' }; currentProvider = saved.provider; $('provider').value = currentProvider; $('baseUrl').value = result.baseUrl; $('model').value = result.model; $('serviceName').value = result.name || ''; setCustom(result.custom); updateProvider(); }).catch(error => status(error.message, 'error')).finally(() => busy(false));
}
